# Generated by Django 3.1.4 on 2021-05-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_comment_likedislike_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
